#!/bin/bash

FILES="src/fSharp32.c src/Instruments.c src/Inputs.c src/Menu.c src/SSD1306.c src/defaultProfiles.c"
OUTPUT="build/fSharp32.elf"
MCU="atmega1284"
FLAGS="-O3 -Wfatal-errors"

readAndExit () {
    read
    exit 1
}

if [ ! -d "build" ]; then
    mkdir "build"
fi

avr-gcc -mmcu=$MCU $FLAGS -o $OUTPUT $FILES || readAndExit
avr-objcopy --dump-section .eeprom=build/defaultProfiles.hex $OUTPUT
avr-size -C --mcu=$MCU $OUTPUT

read

sudo avrdude -p m1284 -c pickit2 -B 800kHz -U flash:w:$OUTPUT:a

read
